baseURL = "https://jia-blog.vercel.app/"
title = "鲸鱼的记忆"
languageCode = "zh-cn"
theme = "PaperMod"
defaultContentLanguage = "zh"
hasCJKLanguage = true
paginate = 12

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "鲸鱼的记忆"
  description = "胡思乱想"
  author = ""
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = false
  ShowFullTextinRSS = false
  disableSpecial1stPost = true
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = true

  [params.homeInfoParams]
    Title = "你好"
    Content = "关于此时此刻"

  [params.profileMode]
    enabled = false

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[menu]
  [[menu.main]]
    identifier = "travels"
    name = "Travels"
    url = "/travels/"
    weight = 5
  [[menu.main]]
    identifier = "photos"
    name = "Photos"
    url = "/photos/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Writing"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
